server:
    write_timeout: 15
    read_timeout: 15
    idle_timeout: 60
    port: 8881
    addr: "0.0.0.0"
database:
    dialect: "postgresql"
    port: 5432
    user: "books"
    password: "123456"
    host: "jenkins_db_example"
    name: "books"
    max_connections: 5