version: '3.3'

services:
  db-postgres:
    image: postgres:9.6-alpine
    restart: always
    container_name: jenkins_db_example
    volumes:
      - ./database/psql/scripts:/docker-entrypoint-initdb.d
    environment:
      - TZ=America/Mexico_City
      - PGTZ=America/Mexico_City
      - POSTGRES_USER=books
      - POSTGRES_DB=books
      - POSTGRES_PASSWORD=123456
  service-go:
    image: golang:1.13-buster
    restart: always
    depends_on: 
     - db-postgres
    container_name: jenkins_service_example
    ports:
        - "8881:8881"
    volumes:
        - .:/go/src/services/jenkins_example
    working_dir: /go/src/services/jenkins_example
    command: ./jenkins-${ENV:-prod}
